# Generated by Django 2.1.3 on 2018-11-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='data_final',
            new_name='fim',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='data_inicio',
            new_name='inicio',
        ),
    ]
