# Generated by Django 2.1.3 on 2018-11-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20181104_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='titulo',
            field=models.CharField(default='aqui', max_length=100),
            preserve_default=False,
        ),
    ]
