# Generated by Django 2.1.3 on 2018-11-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='projetavel',
        ),
    ]
